---
- name:  Finalizing the update
  hosts: undercloud
  tasks:
  - name: Step1.5 Create the update converge command
    copy:
      dest: "/home/stack/update_converge.sh"
      content: |
        openstack overcloud update converge \
            --templates <TODO: path to triple heat templates> \
            -r <TODO: path to roles yaml file> \
            -e <TODO: add the templates used for the deploy here, one per line>
  - name: Step1.6 Make the converge script executable
    file:
      path: /home/stack/update_converge.sh
      state: touch
      mode: u+x,g+x,o+x
  - name: Step2. Run the update finalization command
    shell: /home/stack/update_converge.sh
